/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author felipe
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btnusuario = new javax.swing.JButton();
        btnaudio = new javax.swing.JButton();
        btnAL = new javax.swing.JButton();
        btnAutor = new javax.swing.JButton();
        btncategoria = new javax.swing.JButton();
        btnNarrador = new javax.swing.JButton();
        btnpaisu = new javax.swing.JButton();
        btnpaisAutor = new javax.swing.JButton();
        btnPaisNa = new javax.swing.JButton();
        btnAutLi = new javax.swing.JButton();
        btnEditorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL ADMINISTRADOR");

        Btnusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btnusuario.setText("USUARIO");
        Btnusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnusuarioActionPerformed(evt);
            }
        });

        btnaudio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnaudio.setText("AUDIO");
        btnaudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaudioActionPerformed(evt);
            }
        });

        btnAL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAL.setText("AUDIOLIBRO");
        btnAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALActionPerformed(evt);
            }
        });

        btnAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAutor.setText("AUTOR");
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        btncategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncategoria.setText("CATEGORIA");
        btncategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoriaActionPerformed(evt);
            }
        });

        btnNarrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNarrador.setText("NARRADOR");
        btnNarrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNarradorActionPerformed(evt);
            }
        });

        btnpaisu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnpaisu.setText("PAIS USUARIO");
        btnpaisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaisuActionPerformed(evt);
            }
        });

        btnpaisAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnpaisAutor.setText("PAIS AUTOR");
        btnpaisAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaisAutorActionPerformed(evt);
            }
        });

        btnPaisNa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPaisNa.setText("PAIS NARRADOR");
        btnPaisNa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaisNaActionPerformed(evt);
            }
        });

        btnAutLi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAutLi.setText("AUTORES DE LIBROS");
        btnAutLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutLiActionPerformed(evt);
            }
        });

        btnEditorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditorial.setText("EDITORIAL");
        btnEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPaisNa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btnusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpaisAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpaisu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnaudio, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(btnAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btncategoria)
                            .addComponent(btnNarrador))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAutLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaudio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNarrador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpaisAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaisNa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutLi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpaisu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnusuarioActionPerformed
        
        VistaUsuario vu = new VistaUsuario();
        this.dispose();
        vu.setVisible(true);
        vu.btnregist.setVisible(false);
        vu.btnregresar.setVisible(false);
        
    }//GEN-LAST:event_BtnusuarioActionPerformed

    private void btnpaisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaisuActionPerformed
        
        VistaPais_Usuario vpu = new VistaPais_Usuario();
        this.dispose();
        vpu.setVisible(true);
        
    }//GEN-LAST:event_btnpaisuActionPerformed

    private void btnALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALActionPerformed

        VistaAudiolibro vaL = new VistaAudiolibro();
        this.dispose();
        vaL.setVisible(true);
        
    }//GEN-LAST:event_btnALActionPerformed

    private void btnaudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaudioActionPerformed
        
        VistaAudio vau = new VistaAudio();
        this.dispose();
        vau.setVisible(true);
        
    }//GEN-LAST:event_btnaudioActionPerformed

    private void btncategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoriaActionPerformed
        
        VistaCategoria vc = new VistaCategoria();
        this.dispose();
        vc.setVisible(true);
        
    }//GEN-LAST:event_btncategoriaActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        
        VistaAutor va = new VistaAutor();
        this.dispose();
        va.setVisible(true);
        
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnpaisAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaisAutorActionPerformed
        
        VistaPais_autorI vpa = new VistaPais_autorI();
        this.dispose();
        vpa.setVisible(true);
        
    }//GEN-LAST:event_btnpaisAutorActionPerformed

    private void btnAutLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutLiActionPerformed
        
        Vista_Autores_Libros vaL = new Vista_Autores_Libros();
        this.dispose();
        vaL.setVisible(true);
        
    }//GEN-LAST:event_btnAutLiActionPerformed

    private void btnNarradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNarradorActionPerformed
        
        VistaNarrador vn = new VistaNarrador();
        this.dispose();
        vn.setVisible(true);
        
    }//GEN-LAST:event_btnNarradorActionPerformed

    private void btnPaisNaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaisNaActionPerformed
        
        VistaPais_narrador vpn = new VistaPais_narrador();
        this.dispose();
        vpn.setVisible(true);
        
    }//GEN-LAST:event_btnPaisNaActionPerformed

    private void btnEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialActionPerformed
        
        Vista_Crear_Editorial ve = new Vista_Crear_Editorial();
        this.dispose();
        ve.setVisible(true);
        
    }//GEN-LAST:event_btnEditorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnusuario;
    private javax.swing.JButton btnAL;
    private javax.swing.JButton btnAutLi;
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnEditorial;
    private javax.swing.JButton btnNarrador;
    private javax.swing.JButton btnPaisNa;
    private javax.swing.JButton btnaudio;
    private javax.swing.JButton btncategoria;
    private javax.swing.JButton btnpaisAutor;
    private javax.swing.JButton btnpaisu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
